version: '3.4'

services:
  mongodb:
    container_name: txrouter-mongodb
    image: txscience/tx-persistence:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
      MONGO_NON_ROOT_USERNAME: $MONGO_NON_ROOT_USERNAME
      MONGO_NON_ROOT_PASSWORD: $MONGO_NON_ROOT_PASSWORD

  txrouter:
    container_name: txrouter
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      COMPOSE_PROJECT_NAME: $COMPOSE_PROJECT_NAME
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_COLLECTION: $MONGO_COLLECTION
      MONGO_DATABASE: $MONGO_DATABASE
      MONGO_USERNAME: $MONGO_NON_ROOT_USERNAME
      MONGO_PASSWORD: $MONGO_NON_ROOT_PASSWORD
      ${TXROUTER_INIT_PLUGIN_PATH}: /plugin
      JWT_SECRET: $JWT_SECRET
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TXROUTER_INIT_PLUGIN_PATH}:/plugin
    depends_on:
      - mongodb
    


