version: '3.4'

services:
  mongodb:
    build:
      context: mongodb
    restart: always
    volumes:
      - $MONGODB_DATA_DIR:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
      MONGO_NON_ROOT_USERNAME: $MONGO_NON_ROOT_USERNAME
      MONGO_NON_ROOT_PASSWORD: $MONGO_NON_ROOT_PASSWORD
    expose:
      - 27017
      - 27018
      - 27019

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $API_PORT:8080
    environment:
      MONGO_COLLECTION: $MONGO_COLLECTION
      MONGO_DATABASE: $MONGO_DATABASE
      MONGO_USERNAME: $MONGO_NON_ROOT_USERNAME
      MONGO_PASSWORD: $MONGO_NON_ROOT_PASSWORD
    depends_on:
      - redis
    


