openapi: 3.0.0
info:
  title: PDS Dosing Plugin API
  description: |
    This is the API for a Dosing plug-in that will implement a dosing model.  You can find
    out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "4"
servers:
- url: https://virtserver.swaggerhub.com/krobasky/PDS-API-Plugin/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: dosingModel
  description: Everything about your dosingModel
  externalDocs:
    description: Find out more
    url: http://swagger.io
- name: patient
  description: Access to Patients for which you require dosing guidance
- name: user
  description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: http://swagger.io
- name: guidance
  description: Get records of dosing guidance specific to patient and model
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /decisionTree:
    get:
      tags:
      - dosingModel
      summary: Get decision tree
      operationId: get_decision_tree
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DecisionTree'
      x-openapi-router-controller: swagger_server.controllers.dosing_model_controller
  /patient/{patientId}:
    post:
      tags:
      - dosingModel
      summary: Get patient data
      operationId: get_patient_data
      parameters:
      - name: patientId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: keyClinicalProperties
        content:
          application/json:
            schema: {}
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
        405:
          description: Invalid input
      x-openapi-router-controller: swagger_server.controllers.dosing_model_controller
  /guidance/{pluginId}/{model}:
    post:
      tags:
      - dosingModel
      summary: get guidance
      description: get guidance
      operationId: get_guidance
      parameters:
      - name: pluginId
        in: path
        description: plugin id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: model
        in: path
        description: plugin id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Guidance'
        405:
          description: Invalid input
      x-openapi-router-controller: swagger_server.controllers.dosing_model_controller
components:
  schemas:
    DecisionTree:
      anyOf:
      - $ref: '#/components/schemas/DecisionTreeLeaf'
      - $ref: '#/components/schemas/DecisionTreeInternal'
    DecisionTreeLeaf:
      required:
      - keyClinicalProperties
      - model
      - path
      - pluginId
      type: object
      properties:
        pluginId:
          type: string
        model:
          type: string
        path:
          type: array
          items:
            $ref: '#/components/schemas/DecisionTreeLeaf_path'
        keyClinicalProperties:
          type: object
      additionalProperties: false
    DecisionTreeInternal:
      required:
      - description
      - key
      - subtrees
      - title
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        key:
          type: string
        subtrees:
          type: array
          items:
            $ref: '#/components/schemas/DecisionTreeInternal_subtrees'
    Guidance:
      type: object
    Dosing:
      required:
      - dosingID
      type: object
      properties:
        dosingId:
          type: integer
          format: int64
        drug:
          $ref: '#/components/schemas/Drug'
        dosage:
          type: integer
        units:
          type: string
        route:
          type: string
        complianceSource:
          type: string
        timestamp:
          type: string
        timestampPrecision:
          type: string
      xml:
        name: Dosing
    Drug:
      required:
      - drugID
      type: object
      properties:
        drugId:
          type: integer
          format: int64
        rxnorm:
          type: string
        name:
          type: string
      xml:
        name: Drug
    DecisionTreeLeaf_path:
      required:
      - key
      - value
      type: object
      properties:
        key:
          type: string
        value: {}
    DecisionTreeInternal_subtrees:
      required:
      - subtree
      - value
      type: object
      properties:
        value: {}
        subtree:
          $ref: '#/components/schemas/DecisionTree'

