version: "3.4"
services:
  txrouter-nginx:
    build:
      context: nginx/secure
    volumes:
      - ${TXROUTER_SSL_CERT_DIR}:/a
    ports:
      - ${TXROUTER_API_PORT}:8080
    depends_on:
      - txrouter
